name: ERSpecialEffects
version: 1.0-EB.11
description: Adds Special Effects for the "Jack29's ExplosionRegen" plugin.
main: com.jackalantern29.erspecialeffects.ERSpecialEffects
author: Jackalantern29
api-version: 1.13
depend: [ExplosionRegen]