name: ERSpecialEffects
version: 3.0-EB.2
description: Adds Special Effects for the "ExplosionRegen [Jack29]" plugin.
main: com.jackalantern29.explosionregen.ERSpecialEffects
author: Jackalantern29
api-version: 1.13
depend: [ExplosionRegen]